project:
  type: website
  output-dir: docs

website:
  title: "Ismail (Husain) Bhinderwala"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: lux
    css: styles.css
    toc: true



